spring:
  application:
    name: wxshop-order
  datasource:
    url: jdbc:mysql://localhost:3306/wxorder?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

wxshop:
  rpcorderservice:
    version: 0.0.1

server:
  port: 8081

mybatis:
  config-location: classpath:/db/mybatis/config.xml

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.dahuntun.order.service